name: check

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Kitfly (if kitsite)
        if: ${{ hashFiles('site.yaml') != '' }}
        run: |
          bun install -g kitfly
          kitfly version

      - name: Pre-push Checks
        run: make prepush
